---
- git:
    repo: https://github.com/tj/n
    dest: ~/.n/

- make:
    chdir: ~/.n/
    target: install
    params:
      PREFIX=~/.local

- name: Install Node.js LTS
  shell: |
    source ~/.dotfiles/zshrc
    n lts
  args:
    executable: /bin/zsh

- name: Install npm packages
  environment:
    PATH: '{{ ansible_env.HOME }}/.n/bin'
  npm:
    name: '{{ item }}'
    global: true
  with_items:
    - javascript-typescript-langserver
    - typescript
    - iplocation-cli
