---
- git:
    repo: https://github.com/tj/n
    dest: ~/.n/

- make:
    chdir: ~/.n/
    target: install
    params:
      PREFIX=~/.local

- name: Install Node.js LTS
  shell: |
    source ~/.dotfiles/zshrc
    n lts
  args:
    executable: /bin/zsh
