---
# yamllint disable rule:line-length
# yamllint disable rule:commas
# yamllint disable rule:braces
- hosts: localhost
  vars:
    symlink_dir: '{{ playbook_dir }}/conf'

  roles:
    - role: docker
      become: true
      vars:
        docker_install_compose: false
      tags: docker

    - role: taskwarrior
      tags: taskwarrior

    - role: jobber
      tags: jobber
  tasks:
    - name: Set nopasswd
      tags: nopasswd
      become: true
      blockinfile:
        path: /etc/sudoers
        block: dani ALL=(ALL) NOPASSWD:ALL

    - name: Install apt packages
      become: true
      apt:
        name:
          - htop
          - zsh
          - git
          - httpie
          - curl
          - openvpn
          - net-tools
          - parcellite
          - tmux
          - ripgrep
          - xclip
          - jq
          - git-extras
          - sshfs
          - cmake
          - python-dev
          - build-essential
          - xdotool
          - wmctrl
          - colortest
          - vnstat
          - gparted
          - shellcheck
          - rofi
          - ranger
          - gnome-settings-daemon
          - apt-file
          - direnv
          - xautolock
          - caffeine
          - asciinema
          - network-manager-openvpn-gnome
          - variety
          - feh
          - speedtest-cli
          - i3
          - i3lock
          - ruby-dev
          - libnotify-bin
          - yamllint
          - ncdu
          - inotify-tools
          - flameshot
          - lua5.3

    # It ships by default with i3 and overrides xfce-notifyd. It's also not
    # possible to easily kill like xfce4-nofiyd is, so the notificaiton is long
    # running
    - name: Remove dunst
      become: true
      apt:
        name: dunst
        state: absent

    - name: Install pip packages
      pip:
        name:
          - docker-compose
          - awscli
          - ansible-lint
        state: latest
        extra_args: --user

    - name: Install ruby gems
      gem:
        name: '{{ item }}'
        user_install: true
      with_items:
        - travis
        - gist

    - import_role: name=xorg
      tags: xorg

    - import_role: name=neovim
      tags: neovim

    - import_role: name=fzf
      tags: fzf

    - import_role: name=fd
      tags: fd

    - import_role: name=bat
      tags: bat

#     - import_role: name=gvm
#       tags: gvm

    - import_role: name=n
      tags: n

    - import_role: name=chrome
      tags: chrome

    - import_role: name=alacritty
      tags: alacritty

    - name: antibody
      import_role:
        name: antibody
      tags: antibody

    - import_role: name=i3_gaps
      tags: i3_gaps

    - import_role: name=i3blocks
      tags: i3blocks

    - import_role: name=doctl
      tags: doctl

    - name: hadolint
      import_role:
        name: hadolint
      tags: hadolint

    - import_role: name=terraform
      tags: terraform

    - import_role: name=packer
      tags: packer

    - import_role: name=gcloud
      tags: gcloud

    - import_role: name=hub
      tags: hub

    - import_role: name=ngrok
      tags: ngrok

    - import_role: name=tflint
      tags: tflint

    - import_role: name=nordvpn
      tags: nordvpn

    - import_role: name=enpass
      tags: enpass

    - import_role: name=nextcloud
      tags: nextcloud

    - import_role: name=firefox
      tags: firefox

    - import_role: name=tldr
      tags: tldr

    - import_role: name=bugwarrior
      tags: bugwarrior

    - name: Create symlink parent directories
      tags: symlinks
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '{{ ansible_env.HOME }}/.config/nvim'
        - '{{ ansible_env.HOME }}/.config/git'
        - '{{ ansible_env.HOME }}/.config/asciinema'
        - '{{ ansible_env.HOME }}/.config/pudb'
        - '{{ ansible_env.HOME }}/.ssh'
        - '{{ ansible_env.HOME }}/.i3'
        - '{{ ansible_env.HOME }}/.ptpython'
        - '{{ ansible_env.HOME }}/.config/pypoetry/'
        - '{{ ansible_env.HOME }}/.config/i3blocks/'

    - name: Symlink config files
      tags: symlinks
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        state: link
        force: true
      with_items:
        - { src: '{{ symlink_dir }}/ssh-base-config',  dest: '{{ ansible_env.HOME }}/.ssh/config' }
        - { src: '{{ symlink_dir }}/profile',          dest: '{{ ansible_env.HOME }}/.profile' }
        - { src: '{{ symlink_dir }}/inputrc',          dest: '{{ ansible_env.HOME }}/.inputrc' }
        - { src: '{{ symlink_dir }}/tmux.conf',        dest: '{{ ansible_env.HOME }}/.tmux.conf' }
        - { src: '{{ symlink_dir }}/sqliterc',         dest: '{{ ansible_env.HOME }}/.sqliterc' }
        - { src: '{{ symlink_dir }}/pylintrc',         dest: '{{ ansible_env.HOME }}/.pylintrc' }
        - { src: '{{ symlink_dir }}/pythonrc',         dest: '{{ ansible_env.HOME }}/.pythonrc' }
        - { src: '{{ symlink_dir }}/tern-config',      dest: '{{ ansible_env.HOME }}/.tern-config' }
        - { src: '{{ symlink_dir }}/agignore',         dest: '{{ ansible_env.HOME }}/.agignore' }
        - { src: '{{ symlink_dir }}/gitconfig',        dest: '{{ ansible_env.HOME }}/.gitconfig' }
        - { src: '{{ symlink_dir }}/global-gitignore', dest: '{{ ansible_env.HOME }}/.config/git/ignore' }
        - { src: '{{ symlink_dir }}/i3-config',        dest: '{{ ansible_env.HOME }}/.i3/config' }
        - { src: '{{ symlink_dir }}/Xresources',       dest: '{{ ansible_env.HOME }}/.Xresources' }
        - { src: '{{ symlink_dir }}/ginit.vim',        dest: '{{ ansible_env.HOME }}/.config/nvim/ginit.vim' }
        - { src: '{{ symlink_dir }}/zlogin',           dest: '{{ ansible_env.HOME }}/.zlogin' }
        - { src: '{{ symlink_dir }}/cvsignore',        dest: '{{ ansible_env.HOME }}/.cvsignore' }
        - { src: '{{ symlink_dir }}/asciinema-config', dest: '{{ ansible_env.HOME }}/.config/asciinema/config' }
        - { src: '{{ symlink_dir }}/taskrc',           dest: '{{ ansible_env.HOME }}/.taskrc' }
        - { src: '{{ symlink_dir }}/vitrc',            dest: '{{ ansible_env.HOME }}/.vitrc' }
        - { src: '{{ symlink_dir }}/ptpython_config.py', dest: '{{ ansible_env.HOME }}/.ptpython/config.py' }
        - { src: '{{ symlink_dir }}/pudb.cfg',         dest: '{{ ansible_env.HOME }}/.config/pudb/pudb.cfg' }
        - { src: '{{ symlink_dir }}/i3blocks-config',  dest: '{{ ansible_env.HOME }}/.config/i3blocks/config' }
        - { src: '{{ symlink_dir }}/cookiecutterrc',   dest: '{{ ansible_env.HOME }}/.cookiecutterrc' }
        - { src: '{{ symlink_dir }}/poetry.toml',      dest: '{{ ansible_env.HOME }}/.config/pypoetry/config.toml' }
        - { src: '{{ playbook_dir }}/zshrc',           dest: '{{ ansible_env.HOME }}/.zshrc' }
        - { src: '{{ playbook_dir }}/bashrc',          dest: '{{ ansible_env.HOME }}/.bashrc' }

    - name: Set locales
      become: true
      shell: 'update-locale {{ item }}'
      tags: set-locale
      with_items:
        - LANG=en_US.UTF-8
        - LANGUAGE=en_US
        - LC_CTYPE="en_US.UTF-8"
        - LC_NUMERIC=en_US.UTF-8
        - LC_TIME=en_US.UTF-8
        - LC_COLLATE="en_US.UTF-8"
        - LC_MONETARY=en_US.UTF-8
        - LC_MESSAGES="en_US.UTF-8"
        - LC_PAPER=en_US.UTF-8
        - LC_NAME=en_US.UTF-8
        - LC_ADDRESS=en_US.UTF-8
        - LC_TELEPHONE=en_US.UTF-8
        - LC_MEASUREMENT=en_US.UTF-8
        - LC_IDENTIFICATION=en_US.UTF-8

    - name: Use zsh
      become: true
      tags: use-zsh
      user:
        name: '{{ item }}'
        shell: /bin/zsh
      loop:
        - root
        - dani

    - name: Set the default folder opener
      shell: xdg-mime default pcmanfm.desktop inode/directory
      when: lookup('pipe', 'xdg-mime query default inode/directory') != 'pcmanfm.desktop'
      tags: set-default-file-opener

  - debug:
      msg: Run nextcloud restore to setup files
