---
# Usage
# $ ansible-playbook server_ansible.yml
# -i <inventory>
# --vault-password ~/.vault_password
# -e ansible_become=false
# -e ansible_ssh_user=dani
# --ssh-common-args='-o ProxyJump=jumphost'
# -l <instance>
- hosts: all
  vars:
    ansible_become: false
  tasks:
    - tags: [dependencies, minimal]
      name: Install apt dependencies
      vars:
        ansible_become: true
      apt:
        name: [zsh, net-tools, xclip, httpie]

    - import_role:
        name: neovim
      tags: neovim

    - import_role: name=fzf
      tags: [fzf, minimal]

    - import_role: name=fd
      tags: fd

    - import_role: name=terraform
      tags: terraform

    - import_role: name=packer
      tags: packer

    - import_role: name=ansible
      tags: ansible

    - name: Create dirs
      tags: minimal
      file:
        path: '{{ item }}'
        state: directory
        mode: 0770
        recurse: true
      with_items:
        - '{{ ansible_env.HOME }}/.dotfiles'
        - '{{ ansible_env.HOME }}/.config/nvim'

    - name: Copy shell files
      tags: [rc-files, minimal]
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - src: '{{ playbook_dir }}/zshrc'
          dest: '{{ ansible_env.HOME }}/.zshrc'
        - src: '{{ playbook_dir }}/fzf-helpers.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/fzf-helpers.zsh'
        - src: '{{ playbook_dir }}/git.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/git.zsh'
        - src: '{{ playbook_dir }}/vimrc'
          dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'

    - name: Set zsh as the default shell
      # https://github.com/ansible/ansible/issues/32208
      vars:
        ansible_become: true
      user:
        name: '{{ ansible_user }}'
        shell: /bin/zsh
