---
- hosts: all
  vars:
    ansible_become: false

  tasks:
    - tags: dependencies
      vars:
        ansible_become: true
      name: Install apt dependencies
      apt:
        name: [zsh, net-tools, xclip, httpie]

    - import_role:
        name: neovim
      vars:
        appimage_dest: '{{ ansible_env.HOME }}/.local/bin/nvim'
      tags: neovim

    - import_role:
        name: bat
      vars:
        bat_dest: '{{ ansible_env.HOME }}/.local/bin/bat'
      tags: bat

    - import_role: name=fzf
      tags: fzf

    - import_role: name=fd
      tags: fd

    - name: Create dirs
      file:
        path: '{{ item }}'
        state: directory
        mode: 0770
        recurse: true
      with_items:
        - '{{ ansible_env.HOME }}/.dotfiles'
        - '{{ ansible_env.HOME }}/.config/nvim'

    - name: Copy shell files
      tags: rc-files
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - src: '{{ playbook_dir }}/zshrc'
          dest: '{{ ansible_env.HOME }}/.zshrc'
        - src: '{{ playbook_dir }}/fzf-helpers.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/fzf-helpers.zsh'
        - src: '{{ playbook_dir }}/git.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/git.zsh'
        - src: '{{ playbook_dir }}/vimrc'
          dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'

    - name: Set zsh as the default shell
      # https://github.com/ansible/ansible/issues/32208
      vars:
        ansible_become: true
      user:
        name: '{{ ansible_user }}'
        shell: /bin/zsh
