---
- name: Fetch binary
  shell: >-
    fetch --repo
    https://github.com/denisidoro/navi
    --release-asset=".*x86_64-unknown-linux-musl.*"
    --tag=v{{ navi_tag }} /tmp

- name: Extract the binary
  become: true
  unarchive:
    src: "{{ lookup('fileglob', '/tmp/nav*tar.gz', wantlist=True) | first }}"
    dest: /usr/local/bin/

- name: Clone my cheats
  git:
    repo: https://github.com/danihodovic/cheats.git
    dest: ~/repos/cheats

- name: Create parent dir
  file:
    state: directory
    dest: ~/.local/share/navi/cheats/
    recurse: true

- name: Symlink cheats
  file:
    state: link
    src: ~/repos/cheats
    dest: ~/.local/share/navi/cheats/danihodovic__cheats
    force: true
