---
- name: Install tldr
  become: true
  pip:
    name: tldr

- name: Add update cronjob
  cron:
    user: '{{ ansible_env.USER }}'
    name: tldr-update
    special_time: daily
    job: /usr/local/bin/tldr -u
