---
- name: Install bug warrior
  become: true
  pip:
    # yamllint disable-line rule:line-length
    name: https://github.com/danihodovic/bugwarrior/archive/exclude-pull-requests.zip

- name: Create config dir
  file:
    state: directory
    path: ~/.config/bugwarrior

- name: Symlink config file
  file:
    state: link
    src: '{{ role_path }}/files/bugwarriorrc'
    dest: '{{ ansible_env.HOME}}/.config/bugwarrior/bugwarriorrc'
