---
version: 1.4
prefs:
  runLog:
    type: file
    path: /home/dani/.jobber.log
    maxFileLen: 100m
    maxHistories: 1
jobs:
  tldr:
    time: '0 0 0 * * *'
    cmd: tldr --update

  bugwarrior:
    time: '0 0 0 * * *'
    cmd: zsh -i -c bugwarrior-pull

  docker_prune:
    time: '0 0 0 * * 1'  # Every monday
    cmd: docker system prune --force

  taskwarrior_sync_intheam:
    time: '0 */5 * * * *'
    cmd: zsh -i -c 'task sync'

  update_antibody:
    time: '0 0 0 * * 1'  # Every monday
    cmd: zsh -i -c 'antibody update'

  update_vim_plugins:
    time: '0 0 0 * * 1'  # Every monday
    cmd: zsh -i -c 'antibody update'

  update_apt:
    time: '0 0 0 * * 1'  # Every monday
    cmd: sudo apt update

  update_exist_plus:
    time: '0 30 19 * * *'
    cmd: docker exec -t exist_plus ./manage.py update_exist_data dani

  update_taskwarrior_data:
    time: '0 0 */1 * * *'
    cmd: >-
      zsh -i -c '
      task export | http --print hHb POST localhost:18900/taskwarrior/task-bulk
      "Authorization: Token $EXIST_PLUS_TOKEN"
      '
      &&
      zsh -i -c '
      timew export |
      http --print hHb POST localhost:18900/taskwarrior/task-interval-bulk
      "Authorization: Token $EXIST_PLUS_TOKEN"
      '

  rclone_sync:
    time: '0 */5 * * * *'
    cmd: >-
      /home/dani/repos/rclonesync-V2/rclonesync.py
      /home/dani/Nextcloud nextcloudwebo:
