---
- name: Clone the repo
  git:
    repo: '{{ repo }}'
    dest: '{{ dir }}'
    depth: 1

- name: Run cmake
  shell: cmake -DCMAKE_BUILD_TYPE=release .
  args:
    chdir: '{{ dir }}'

- name: Run make
  community.general.make:
    chdir: '{{ dir }}'

- name: Run make install
  become: true
  community.general.make:
    chdir: '{{ dir }}'
    target: install
