---
- name: Install dependencies
  apt:
    name: perl-modules-5.26
  become: true

- name: Install diff-so-fancy
  get_url:
    # yamllint disable-line rule:line-length
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: '{{ diff_so_fancy_dest }}'
    mode: 0770
