---
# yamllint disable rule:line-length
- become: true
  block:
    - name: Upgrade system firmware
      apt:
        name: fwupd
        update_cache: true

    - name: Refresh
      shell: |
        fwupdmgr get-devices
        fwupdmgr refresh --force

    - name: Get updates
      shell: fwupdmgr get-updates
      register: _result
      failed_when: _result.rc != 0 and "No updatable devices" not in _result.stderr

    - name: Update
      shell: fwupdmgr update
      register: _result
      failed_when: _result.rc != 0 and "has no available firmware updates" not in _result.stderr
