---
- name: Install i3-gaps dependencies
  become: true
  apt:
    name:
      - libxcb1-dev
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libev-dev
      - libxcb-cursor-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - autoconf
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb-shape0-dev
      - automake
      - meson

- name: Clone i3-gaps
  git:
    repo: https://www.github.com/Airblader/i3
    dest: '{{ ansible_env.HOME }}/repos/i3-gaps'
    version: gaps-next
  register: i3_gaps

- name: Compile and install i3-gaps
  args:
    chdir: '{{ ansible_env.HOME }}/repos/i3-gaps'
  shell: |
    mkdir -p build && cd build/
    meson ..
    ninja
    meson install
