---
- become: true
  block:
    - name: Add enpass repository
      apt_repository:
        repo: deb https://apt.enpass.io/ stable main

    - name: Add enpass signing key
      apt_key:
        url: https://apt.enpass.io/keys/enpass-linux.key
        id: 6F7565879798C2FC

    - name: Install enpass
      apt:
        name: enpass

    - name: Add binary to $PATH
      file:
        state: link
        src: /opt/enpass/Enpass
        dest: /usr/local/bin/enpass
