---
- name: Install dependencies
  become_user: root
  apt:
    name: [git, curl]

- name: Clone fzf
  # become_user: dani
  git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: ~/.fzf
    accept_hostkey: true

- name: Install fzf
  # become_user: dani
  shell: ~/.fzf/install --key-bindings --completion --no-update-rc
