---
- name: Install pip
  become: true
  apt:
    name: python-pip

- name: Install pip dependencies
  pip:
    name: [jmespath, boto, docker, docker-compose]

- name: Install ansible
  pip:
    name: ansible
    version: '{{ version }}'
