---
- name: Get dropbox debian package
  get_url:
    # yamllint disable-line rule:line-length
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
    dest: /tmp/dropbox.deb
    mode: 0755

- name: Install dropbox
  apt:
    deb: /tmp/dropbox.deb
