---
- name: Install dependencies
  become: true
  apt:
    name:
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - liblzma-dev

- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ ansible_env.HOME }}/.pyenv'
