---
- name: Install docker role
  become: true
  import_role:
    name: geerlingguy.docker
  vars:
    docker_users: ['{{ ansible_env.USER }}']

- name: Add a cronjob for `docker system prune`
  tags: cron
  cron:
    name: docker_system_prune
    minute: 0
    hour: 0
    weekday: 1
    job: 'docker system prune -f >> /var/log/docker_system_prune.log 2>&1'
