---
- set_fact:
    docker_url: https://download.docker.com/linux/ubuntu/dists

- name: Install docker packages
  become: true
  apt:
    # yamllint disable-line rule:line-length
    deb: '{{ docker_url }}/{{ ansible_distribution_release }}/pool/stable/amd64/{{ item }}'
  with_items:
    - containerd.io_1.2.2-1_amd64.deb
    - docker-ce-cli_18.09.1~3-0~ubuntu-cosmic_amd64.deb
    - docker-ce_18.09.1~3-0~ubuntu-cosmic_amd64.deb

- name: Add user to docker
  become: true
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: true

- name: Add a cronjob for `docker system prune`
  tags: cron
  cron:
    name: docker_system_prune
    hour: 0
    weekday: 1
    job: 'docker system prune -f >> /var/log/docker_system_prune.log 2>&1'
