---
- set_fact:


- name: Install docker packages
  become: true
  apt:
    # yamllint disable-line rule:line-length
    deb: '{{ docker_url }}/{{ ansible_distribution_release }}/pool/stable/amd64/{{ item }}'
  with_items:
    - '{{ docker_containerd_version }}'
    - '{{ docker_cli_version }}'
    - '{{ docker_daemon_version }}'

- name: Add user to docker
  become: true
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: true

- name: Add a cronjob for `docker system prune`
  tags: cron
  cron:
    name: docker_system_prune
    hour: 0
    weekday: 1
    job: 'docker system prune -f >> /var/log/docker_system_prune.log 2>&1'
