---
- name: Install dependencies
  apt:
    name: curl

- name: Install antibody
  become: true
  shell: curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

- name: Install antibody plugins
  shell: 'antibody bundle < {{ role_path }}/files/antibody.txt'
