---
- name: Get latest release
  uri:
    url: https://api.github.com/repos/jwilm/alacritty/releases/latest
    timeout: 5
  register: latest_release
  changed_when: false

- name: Get download url
  set_fact:
    alacritty_download_url: >
      {{
        latest_release.json.assets |
        to_json | from_json |
        json_query(
          "[?contains(name, 'x86_64')].browser_download_url | [0]"
        )
      }}

- name: Download
  get_url:
    url: '{{ alacritty_download_url }}'
    dest: /tmp/alacritty.tar.gz
    force: true

- name: Unarchive
  unarchive:
    src: /tmp/alacritty.tar.gz
    dest: /tmp/

- name: Move to bin
  become: true
  copy:
    src: /tmp/alacritty
    dest: /usr/local/bin/
    mode: 0755

- name: Create parent dir
  file:
    state: directory
    path: ~/.config/alacritty/
    recurse: true

- name: Symlink config file
  file:
    state: link
    src: '{{ role_path }}/files/alacritty.yml'
    dest: ~/.config/alacritty/alacritty.yml
