---
- name: Install dependencies
  become: true
  apt:
    name: '{{ item }}'
  with_items:
    - binutils
    - bison
    - gcc

- name: Install gvm
  args:
    executable: /bin/bash
    creates: '{{ ansible_env.HOME }}/.gvm/bin/gvm'
  shell: |
    set -o pipefail
    url=https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    curl -s -S -L $url | bash
