---
- name: Install xsel for yank
  become: true
  apt:
    name: xsel

- name: Install jmespath on the Ansible controller
  delegate_to: localhost
  pip:
    name: jmespath
    extra_args: --user

- name: Create directory
  file:
    state: directory
    path: '{{ neovim_dest | dirname }}'

- name: Get latest release
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/tags/nightly
    timeout: 5
  register: neovim_latest_release
  changed_when: false

- name: Get download url
  set_fact:
    neovim_download_url: >
      {{
        neovim_latest_release.json.assets |
        to_json | from_json |
        json_query(
          "[?contains(name, 'nvim.appimage')].browser_download_url | [0]"
        )
      }}

- name: Download appimage
  get_url:
    url: '{{ neovim_download_url }}'
    dest: '{{ neovim_dest }}'
    mode: 0770
    force: true

- name: Install pip package
  pip:
    name: neovim

- set_fact:
    vim_plug_path: ~/.local/share/nvim/site/autoload/plug.vim

- name: Create vim-plug dir
  file:
    state: directory
    path: '{{ vim_plug_path | dirname }}'

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ vim_plug_path }}'

- include_tasks: ./language_servers.yml
