---
global:
  scrape_interval: 30s

rule_files:
  - node_exporter_rules.yml
  - node_exporter_alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
